name: CI - DBT Autoscaling Slim
on:
  pull_request:
    types: [synchronize, labeled]

jobs:
  autoscaling:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'CI') }}
    runs-on: ubuntu-latest
    env:
      DBT_CLOUD_SERVICE_TOKEN: ${{ secrets.DBT_CLOUD_SERVICE_TOKEN }}
      DBT_CLOUD_ACCOUNT_ID: <INSERT>
      JOB_ID: <INSERT>
      PULL_REQUEST_ID: ${{ github.event.number }}
      GIT_SHA: ${{ github.event.pull_request.head.sha }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install DBTC
        run: |
          pip install dbtc==0.3.3
      - name: Run Autoscaling Slim CI
        run: |
          SO="dbt_cloud_pr_"$JOB_ID"_"$PULL_REQUEST_ID
          dbtc trigger-autoscaling-ci-job \
            --job-id=$JOB_ID \
            --payload='{"cause": "Autoscaling Slim CI!","git_sha":"'"$GIT_SHA"'","schema_override":"'"$SO"'","github_pull_request_id":'"$PULL_REQUEST_ID"'}' \
            --no-should-poll
