name: CI - Spectacles

on:
  pull_request:
    branches-ignore:
      - master
    types: [synchronize, labeled]

jobs:
  spectacles:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'CI') && github.event.pull_request.merged != true }}
    runs-on: ubuntu-latest
    env:
      LOOKER_BASE_URL: https://<INSERT>.looker.com
      LOOKER_CLIENT_ID: ${{ secrets.LOOKER_CLIENT_ID }}
      LOOKER_CLIENT_SECRET: ${{ secrets.LOOKER_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Spectacles
        run: |
          pip install spectacles==2.3.8
      - name: Run Spectacles Assert Validation
        run: |
          spectacles assert --project narrativ
      - name: Run Spectacles LookML Validation
        run: |
          spectacles lookml --project narrativ --severity error
